# Generated by Django 5.1.4 on 2024-12-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('idade', models.IntegerField()),
                ('altura', models.FloatField()),
                ('clube', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('posicao', models.CharField(max_length=100)),
                ('numeroTotalDeJogos', models.IntegerField()),
                ('numeroDeJogosComoTitular', models.IntegerField()),
            ],
        ),
    ]
