# Generated by Django 5.2.3 on 2025-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='clube',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicao',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='atleta',
            index=models.Index(fields=['nome'], name='atleta_app__nome_a2d26b_idx'),
        ),
        migrations.AddIndex(
            model_name='atleta',
            index=models.Index(fields=['cpf'], name='atleta_app__cpf_dae956_idx'),
        ),
        migrations.AddIndex(
            model_name='atleta',
            index=models.Index(fields=['clube'], name='atleta_app__clube_49dc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='atleta',
            index=models.Index(fields=['posicao'], name='atleta_app__posicao_9875aa_idx'),
        ),
        migrations.AddIndex(
            model_name='atleta',
            index=models.Index(fields=['nome', 'clube'], name='atleta_app__nome_eb7a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='atleta',
            index=models.Index(fields=['clube', 'posicao'], name='atleta_app__clube_e14255_idx'),
        ),
    ]
