name: Enforce branch naming rules

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|fix|hotfix)/ ]]; then
            echo "❌ Branch '$BRANCH_NAME' does not follow naming conventions (feature/, fix/, hotfix/)."
            exit 1
          fi
